# vim: set ft=yaml ts=2 expandtab:
---

name: runner debug

on: 

  push:
  pull_request:
  workflow_dispatch:

jobs:
  crun:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Container Image
        run: |
          cat - >Containerfile <<EOF
          FROM ubuntu:22.04
          RUN apt-get update && apt-get install -y systemd
          CMD ["/lib/systemd/systemd"]
          EOF
          podman build --tag ghtest .
      - name: Run Container
        run: podman run --systemd always -d ghtest
          
  debug:

    runs-on: ubuntu-22.04

    steps:
         
      - name: checkout collection ansible
        uses: actions/checkout@v4
        with:
          path: src
    
      - name: checkout collection ansible
        uses: actions/checkout@v4
           
      - name: debug environment 2
        run: |
           pwd
           echo $HOME
           whoami
           echo github_workflow $GITHUB_WORKSPACE
           tree $HOME/work

      - name: python
        run: |
          echo $PATH
          which python
          ls -l /opt/hostedtoolcache/Python/
          set -x
          which python3
          python3 -c "import yaml"

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: python script
        run: |
          pip install pyyaml
          which python3
          python3 -c "import yaml"
          
      - name: docker version
        run: |
          docker --version
          dockerd --version

      - name: list local docker images
        run: docker images

      - name: check if apparmor is active
        run: sudo apparmor_status
        
      - name: check if podman is available
        run: |
          podman --version
          
      - name: /etc/docker
        run: ls -l /etc/docker

      - name: get kernel config
        run: cat /boot/config-$(uname -r)

      - name: Get kernel arguments of running kernel
        run: cat /proc/cmdline
        
      - name: get mounted filesystems
        run: df -h

      - name: get all installed packages
        run: dpkg -l

      - name: get all installed python packages
        run: pip list
        
      - name: get info about ansible
        run: ansible --version
      
      - name: get info about ansible-playbook
        run: ansible-playbook --version
      
      - name: get info about galaxy
        run: ansible-galaxy --version

      - name: get ansible facts
        run: ansible localhost -m setup
        
      - name: ls
        run: |
          pwd
          ls -l
        
      - name: install venv requirements
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv

      - name: get environment
        run: env

      - name: set path
        run: export PATH=/home/runner/.local/bin:$PATH

      - name: get environment
        run: env
      
      - name: Network setup
        run: |
          ip addr li
          ip ro li
          sudo iptables -L -v
          sudo iptables -L -v -t nat
          docker network ls
          docker network inspect bridge
...
