---
name: runner debug

on: 
  - push
  - pull_request  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: get all installed packages
        run: dpkg -l

      - name: get info about ansible
        run: ansible --version

      - name: checkout our github project
        uses: actions/checkout@v1
      
      - name: install requirements
        run: |
          sudo apt-get install python-wheel
          pip2 install -r requirements.txt

      - name: get environment
        run: env

      - name: get molecule version
        run: pip show molecule
...