# vim: set ft=yaml ts=2 expandtab:
---

name: runner debug

on: 
  - push
  - pull_request  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: /etc/docker
        run: ls -l /etc/docker

      - name: get kernel config
        run: cat /boot/config-$(uname -r)

      - name: get mounted filesystems
        run: df -h

      - name: get all installed packages
        run: dpkg -l

      - name: get all installed python packages
        run: pip list
        
      - name: get info about ansible
        run: ansible --version

      - name: checkout our github project
        uses: actions/checkout@v1
      
      - name: ls
        run: ls -l /usr/bin
        
      - name: install requirements
        run: |
          sudo apt-get install python-wheel
          pip2 install -r requirements.txt

      - name: get environment
        run: env

      - name: set path
        run: export PATH=/home/runner/.local/bin:$PATH

      - name: get molecule version
        run: pip show molecule

      - name: get environment
        run: env

...
