# vim: set ft=yaml ts=2 expandtab:
---

name: runner debug

on: 

  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

      - name: debug environment
        run: |
           pwd
           echo $HOME
           whoami
           ls -lRh
           
      - name: checkout collection ansible
        uses: actions/checkout@v4
        with:
          path: src

      - name: checkout collection ansible
        uses: actions/checkout@v4
           
      - name: debug environment 2
        run: |
           pwd
           echo $HOME
           whoami
           ls -lRh
           
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '2.7'

      - name: python
        run: |
          echo $PATH
          which python
          ls -l /opt/hostedtoolcache/Python/
          ls /opt/hostedtoolcache/Python/2.7.18/x64/bin
         
      - name: virtualenv
        run: |
          pip install virtualenv
          ansible-playbook src/venv.yml -e "arg_virtualenv_command='virtualenv -p python2'"
          . /tmp/test/bin/activate
          ansible --version

      - name: docker version
        run: |
          docker --version
          dockerd --version

      - name: list files in moby
        run: |
          dpkg -L moby-cli

      - name: list files in moby
        run: |
          dpkg -L moby-engine

      - name: list files in moby
        run: |
          dpkg -L moby-containerd

      - name: list local docker images
        run: docker images
        
      - name: check if podman is available
        run: podman --version
        
      - name: /etc/docker
        run: ls -l /etc/docker

      - name: get kernel config
        run: cat /boot/config-$(uname -r)

      - name: get mounted filesystems
        run: df -h

      - name: get all installed packages
        run: dpkg -l

      - name: get all installed python packages
        run: pip list
        
      - name: get info about ansible
        run: ansible --version
      
      - name: get info about ansible-playbook
        run: ansible-playbook --version
      
      - name: get info about galaxy
        run: ansible-galaxy --version

      - name: get ansible facts
        run: ansible localhost -m setup
        
      - name: ls
        run: |
          pwd
          ls -l
          
      - name: checkout our github project
        uses: actions/checkout@v1
      
      - name: ls
        run: |
          pwd
          ls -l
          ls -l /usr/bin
        
      - name: install venv requirements
        run: |
          sudo apt-get update
          sudo apt-get install python3.8-venv

      - name: get environment
        run: env

      - name: set path
        run: export PATH=/home/runner/.local/bin:$PATH

      - name: get environment
        run: env
      
      - name: Network setup
        run: |
          ip addr li
          ip ro li
          sudo iptables -L -v
          sudo iptables -L -v -t nat
          docker network ls
          docker network inspect bridge
...
