# vim: set ft=yaml ts=2 expandtab:
---

name: matrix test

on: 

  - push

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

      matrix:

        os:
          # there are special dependencies for fedora35 that are probably not necessary anymore
          - fedora35
          - c8s
          - c9s
          - ubuntu2110

        python_version:
          - '3.6'
          - '3.8'
          - '3.9'
          - '3.10'

        ansible_version:
          - '2.9'
          - '2.10'
          - '2.11'
          - '2.12'

        exclude:
 
          - os: fedora35
            ansible_version: '2.9'

          - os: fedora35
            python_version: '3.6'
          - os: fedora35
            python_version: '3.8'
          - os: fedora35
            python_version: '3.9'

          - os: c8s
            python_version: '2.10'
          - os: c8s
            python_version: '3.10'
            ansible_version: '2.12'

          - os: c9s
            ansible_version: '2.9'
          - os: c9s
            python_version: '3.6'
          - os: c9s
            python_version: '3.8'
          - os: c9s
            python_version: '3.9'

          - os: ubuntu2110
            ansible_version: '2.9'
          - os: ubuntu2110
            python_version: '3.6'
          - os: ubuntu2110
            python_version: '3.8'

        include:
 
          # for now only with installed gcc and libffi-devel
          # waiting for python 3.10 wheel for cffi
          #
          - os: fedora35
            image: quay.io/fedora/fedora:35-x86_64
 
          - os: c9s
            image: quay.io/centos/centos:stream9-development
 
          - os: c8s
            image: quay.io/centos/centos:stream8
 
          # ubuntu impish
          - os: ubuntu2110
            image: docker.io/ubuntu:21.10
        
  
    steps:
      
      - name: matrix
        run: |
          echo ${{ matrix.os }} - ${{ matrix.python_version }} - ${{ matrix.ansible_version }}
 
...
